### ISSUE TITLE
Minor issues about 'Edit Name' link

### ISSUE THREAD

**Issue by diclee** [koding/koding#8809]
## Current Behavior
![image](https://cloud.githubusercontent.com/assets/8261892/17664701/af48c92c-62fe-11e6-8a9d-d2aead6fcf69.png)

- [x] 'Edit Name' on virtual machines tab shows text cursor instead of a link cursor.

- [x] Link doesn't disappear when you click on it. (as it's on stack editor)

**Comment by hakankaradis** [comment]
This issues are fixed with this pr #8796

**Comment by diclee** [comment]
@hakankaradis second item on the above list is still not fixed. 'Edit Name' link behavior should be as it's on stack editor.

Behavior on stack editor:
![gif](http://g.recordit.co/lPYXoMOmmB.gif)

Behavior on virtual machines tab:
![gif](http://g.recordit.co/BXPTgnAu5G.gif)

**Comment by diclee** [comment]
Verify passed on latest.
