### ISSUE TITLE
Doc links are broken for some of the guides.

### ISSUE THREAD

**Issue by diclee** [koding/koding#9433]
## Current Behavior
![image](https://cloud.githubusercontent.com/assets/8261892/19862524/67756cf4-9f99-11e6-8693-fbee627b980e.png)

- docs link on stack script page

- 'View Guide' link for GitLab, Intercom and Chatlio on integrations tab

- 'View Guide' link for KD Cli, Koding OS X App and API Access on utilities tab

**Comment by sinan** [comment]
> docs link on stack script page
> 'View Guide' link for GitLab, Intercom and Chatlio on integrations tab

I fixed the immediate issue for the ones above with https://github.com/koding/koding/pull/9436

> 'View Guide' link for KD Cli, Koding OS X App and API Access on utilities tab

@kwagdy please migrate these too.

**Comment by diclee** [comment]
@kwagdy 'View Guide' links for KD Cli, Koding OS X App and API Access are still broken. Can you please check and fix?

**Comment by kwagdy** [comment]
**Koding OS X app** guide added
**Gitlab** is a coming soon page, will work on it, or shall we reference the one Gokmen published (https://gitlab.com/help/user/project/koding.md)?
**Intercom** is a coming soon page, will need help to create this one, I will reach out and get it done
**Chatlio** is a coming soon page, will need help to create this one, I will reach out and get it done

**Comment by gokmen** [comment]
@kwagdy we need to write down another one, that one is about integrating gitlab with koding but the feature mentioned there is koding with gitlab integration and most of the flow is different in this case.

**Comment by kwagdy** [comment]
@gokmen awesome, when would have time so I can discuss it with you and start writing our version?

**Comment by diclee** [comment]
Verify passed for broken links.
